insert into model_drone (name) values ('Lightweight');
insert into model_drone (name) values ('Middleweight');
insert into model_drone (name) values ('Cruiserweight');
insert into model_drone (name) values ('Heavyweight');
insert into state_drone (name) values ('IDLE');
insert into state_drone (name) values ('LOADING');
insert into state_drone (name) values ('LOADED');
insert into state_drone (name) values ('DELIVERING');
insert into state_drone (name) values ('DELIVERED');
insert into state_drone (name) values ('RETURNING');
insert into medication (name, weight, code) values ('Name-1_0', 200, 'CODE_1');
insert into medication (name, weight, code) values ('Name-2', 200, 'CODE_2');
insert into medication (name, weight, code) values ('Name_3', 200, 'CODE_3');
insert into drone (serial_number, weight_limit, battery_capacity, model_drone_id, state_drone_id) values ('xde', 500, 90, 1, 1);
insert into drone (serial_number, weight_limit, battery_capacity, model_drone_id, state_drone_id) values ('xdew', 500, 90, 1, 1);
insert into drone (serial_number, weight_limit, battery_capacity, model_drone_id, state_drone_id) values ('xdea', 500, 90, 1, 1);